# Generated by Django 3.0.5 on 2020-04-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('IFSCCode', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50, verbose_name='bank-name')),
            ],
        ),
    ]
